// topics
export const GET_TOPICS = "GET_TOPICS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_SINGLE_TOPIC = "SET_SINGLE_TOPIC";
export const DELETE_TOPIC_DIALOG = "DELETE_TOPIC_DIALOG";
export const TOPIC_VIEW_TYPE = "TOPIC_VIEW_TYPE";
export const TOPIC_SORT_FILTER = "TOPIC_SORT_FILTER";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const EDIT_TOPIC = "EDIT_TOPIC";
export const UPDATE_COMMENT_COUNT = "UPDATE_COMMENT_COUNT";

// user
export const SET_USER_DATA = "SET_USER_DATA";
export const X_AUTH_TOKEN = "X_AUTH_TOKEN";
export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_REPORT_OPEN = "MODAL_REPORT_OPEN";
export const MODAL_REPORT_COMMENT_OPEN = "MODAL_REPORT_COMMENT_OPEN";
export const MODAL_SHARE_OPEN = "MODAL_SHARE_OPEN";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SEARCH_ALL_USERS = "SEARCH_ALL_USERS";
export const BAN_AND_UNBANUSER = "BAN_AND_UNBANUSER";
export const REPORTED_USER = "REPORTED_USER";
export const BAN_REPORTED_USER = "BAN_REPORTED_USER";
export const DELETE_REPORT = "DELETE_REPORT";
export const GET_REPORTED_USERS = "GET_REPORTED_USERS";
export const MODAL_SETTING_OPEN = "MODAL_SETTING_OPEN";

//bot
export const BOT_MODAL_SETTING_OPEN = "BOT_MODAL_SETTING_OPEN";

// gift
export const OPEN_GIFT = "OPEN_GIFT";
export const SET_ELEMENT_ID = "SET_ELEMENT_ID";
export const SET_GIFT_TYPE = "SET_GIFT_TYPE";

//broadcast
export const OPEN_BROADCAST = "OPEN_BROADCAST";
export const SET_BROADCAST_ELEMENT_ID = "SET_BROADCAST_ELEMENT_ID";
export const SET_PROMOTION_CHARGE = "SET_PROMOTION_CHARGE";
export const OPEN_PROMOTION_PRICE = "OPEN_PROMOTION_PRICE";
export const SET_ALL_PROMOTED_POSTS = "SET_ALL_PROMOTED_POSTS";
export const SET_ACTIVE_PROMOTED_POSTS = "SET_ACTIVE_PROMOTED_POSTS";
export const REFRESH_PROMOTED_POSTS = "REFRESH_PROMOTED_POSTS";
export const INCLUDE_PROMOTED_POST = "INCLUDE_PROMOTED_POST";

// export const SET_ELEMEN = "OPEN_BROADCAST";

// comment
export const TOGGLE_COMMENT = "TOGGLE_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const SET_CURRENT_COMMENT_PAGE = "SET_CURRENT_COMMENT_PAGE";
export const DELETE_COMMENT = "DELETE_COMMENT";

//search
export const GET_SEARCH = "GET_SEARCH";

// site
export const GET_SITE = "GET_SITE";
export const GET_TOPIC_FOR_SITE = "GET_TOPIC_FOR_SITE";
export const GET_URL = "GET_URL";

// language
export const SET_LANGUAGE = "SET_LANGUAGE";
export const GET_LANGUAGE = "GET_LANGUAGE";

// profile
export const GET_USER_TOPICS = "GET_USER_TOPICS";
export const GET_USER_COMMENTS = "GET_USER_COMMENTS";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_FOLLOWERS = "GET_USER_FOLLOWERS";
export const GET_USER_FOLLOWING = "GET_USER_FOLLOWING";
export const SET_USER_CURRENT_PAGE = "SET_USER_CURRENT_PAGE";
export const SET_USERNAME = "SET_USERNAME";
export const GET_USER_SUGGESTIONS = "GET_USER_SUGGESTIONS";

// notification
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const MODAL_VERIFY_DOMAIN_OPEN = "MODAL_VERIFY_DOMAIN_OPEN";
export const MODAL_ADD_DOMAIN_OPEN = "MODAL_ADD_DOMAIN_OPEN";
export const SET_USER_DOMAIN_DATA = "SET_USER_DOMAIN_DATA";

export const MODAL_VERIFY_YOUTUBE_OPEN = "MODAL_VERIFY_YOUTUBE_OPEN";
export const SET_USER_CHANNEL_DATA = "SET_USER_CHANNEL_DATA";

//group
export const OPEN_ADD_MODERATOR = "OPEN_ADD_MODERATOR";
export const ADD_MODERATOR_DETAILS = "ADD_MODERATOR_DETAILS";

//cryptos
export const GET_CRYPTOS = "GET_CRYPTOS";
export const OPEN_CRYPTO_PRICE = "OPEN_CRYPTO_PRICE";
export const UPDATE_CRYPTO_PRICE = "UPDATE_CRYPTO_PRICE";
